apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: vtakis/primes:arm
      volumeMounts:
        - mountPath: /home/app/primes
          name: task-pv-storage
  hostNetwork: true
  nodeSelector: 
    colour: green



     #   livenessProbe:
     #     exec:
     #       command: ["python", "my_script.py",">","data/out.txt"]  