apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: forcluster
spec:
  storageClassName: boom
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ellycris.di.uoa.gr 
    path: "/home/pcomp/mnt/tv"